### ISSUE TITLE
Imagen responsive

### ISSUE THREAD

**Issue by willy5360** [BernatLl/Digital-Postcard-html-css#1]
https://github.com/BernatLl/Digital-Postcard-html-css/blob/247b7e8c00cd10175ba75028d6e0640586b11e71/main.css#L25

Acordaros chicos que para hacer una imagen sea responsive debeis asignar el width: x% , donde "x" sera el tamaño que querais pintar en el front, y un height: auto

**Comment by NaincyKumariKnoldus** [comment]
Hey @willy5360 ! I really want to do this. Can I please?
¡Oye @willy5360 ! Realmente quiero hacer esto. ¿Puedo porfavor?

**Comment by willy5360** [comment]
Hi, nancy. I'm a teacher assistant in a programming course, and I'm reviewing my students projects. Please do not interfere in these issues, since they are the ones who need to fix them.

**Comment by NaincyKumariKnoldus** [comment]
okay @willy5360 no problem

**Comment by BernatLl** [comment]
@willy5360 ya está corregido!!

**Comment by willy5360** [comment]
@BernatLl  Genial, lo unico que tendrias que hacer es volver a enviar este enlace de repositotio por el breathcode
